use reqwest::Url;

pub fn get_seeds() -> Vec<Url> {
    vec![
        // News
        "https://dr.dk",
        "https://tv2.dk",
        "https://berlingske.dk",
        "https://politiken.dk",
        "https://ekstrabladet.dk",
        "https://bt.dk",
        "https://information.dk",
        "https://finans.dk",
        "https://arbejderen.dk",
        "https://jyllands-posten.dk",
        "https://kristeligt-dagblad.dk",
        "https://weekendavisen.dk",
        "https://lokalavisen.dk",
        "https://tv2nord.dk",
        "https://tv2ostjylland.dk",
        "https://tv2lorry.dk",
        "https://tv2fyn.dk",
        "https://tv2east.dk",
        "https://tv2kosmopol.dk",
        "https://nordjyske.dk",
        // Tech & Business
        "https://version2.dk",
        "https://computerworld.dk",
        "https://ing.dk",
        "https://itek.dk",
        "https://detdigitaleselskab.dk",
        "https://erhvervsliv.dk",
        "https://borsen.dk",
        "https://finanswatch.dk",
        "https://epn.dk",
        "https://startupcentral.dk",
        // Classifieds & Marketplaces
        "https://dba.dk",
        "https://guloggratis.dk",
        "https://bilbasen.dk",
        "https://autouncle.dk",
        "https://boligsiden.dk",
        "https://edc.dk",
        "https://nybolig.dk",
        "https://home.dk",
        "https://danbolig.dk",
        "https://lejebolig.dk",
        // Forums & Communities
        "https://eksperten.dk",
        "https://hifi4all.dk",
        "https://forums.dk",
        "https://amino.dk",
        "https://babyverden.dk",
        "https://motorsite.dk",
        "https://detektivforumet.dk",
        "https://outdoor.dk",
        "https://sportscykler.dk",
        "https://cykelmagasinet.dk",
        // Government & Public
        "https://denmark.dk",
        "https://politi.dk",
        "https://skat.dk",
        "https://borger.dk",
        "https://sundhed.dk",
        "https://retsinformation.dk",
        "https://dst.dk",
        "https://dtu.dk",
        "https://ku.dk",
        "https://au.dk",
        "https://sdu.dk",
        "https://ruc.dk",
        "https://cbs.dk",
        "https://itu.dk",
        "https://aau.dk",
        // Retail & Shopping
        "https://pricerunner.dk",
        "https://elgiganten.dk",
        "https://power.dk",
        "https://coolshop.dk",
        "https://av-cables.dk",
        "https://komplett.dk",
        "https://computersalg.dk",
        "https://planetz.dk",
        "https://hm.com",
        "https://zalando.dk",
        "https://boozt.com",
        "https://magasin.dk",
        "https://illum.dk",
        // Health & Lifestyle
        "https://helse.dk",
        "https://netdoktor.dk",
        "https://apoteket.dk",
        "https://bodylab.dk",
        "https://medicinraadet.dk",
        "https://cancer.dk",
        "https://hjerteforeningen.dk",
        "https://diabetesforeningen.dk",
        // Sports
        "https://dbu.dk",
        "https://dif.dk",
        "https://bold.dk",
        "https://tipsbladet.dk",
        "https://superliga.dk",
        "https://speedwaynews.dk",
        "https://cykling.dk",
        // Misc high-link-count
        "https://denstoredanske.dk",
        "https://jobindex.dk",
        "https://ofir.dk",
        "https://careerjet.dk",
        "https://rejseplanen.dk",
        "https://danskebank.dk",
        "https://nordea.dk",
        "https://jyskebank.dk",
    ]
    .into_iter()
    .filter_map(|u| Url::parse(u).ok())
    .collect()
}
